version: '3'
services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile-back-end
    image: softy-pinko-back-end:task4
    ports:
      - "5253:5253"

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile-front-end
    image: softy-pinko-front-end:task4
    ports:
      - "80:80"
    depends_on:
      - back-end
