# Utilise l'image officielle d'Ubuntu
FROM ubuntu:latest

# Met à jour les paquets du système et effectue une mise à jour des paquets installés
RUN apt-get update && apt-get upgrade -y

# Affiche "Hello, World!" lorsque le conteneur est exécuté
CMD echo "Hello, World!"
